### ISSUE TITLE
보관함 화면에서 "로그인" 버튼을 클릭하면 로그인이 필요한 서비스라는 Popup이 노출됨

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#1007]
### 설명

바로 로그인 페이지가 노출되는게 자연스러워보여요

https://github.com/user-attachments/assets/1665997d-bf05-4c24-9b41-cdc6bf441e29

**Comment by KangTaeHoon** [comment]
내 리스트 탭은 수정했는데, 좋아요 탭은 까먹은듯,,
