### ISSUE TITLE
간헐적으로 검색 -> 리스트탭 -> 플리 상세 접근 후 뒤로갈 시 리스트 탭 타이틀이 사라져있음

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#1011]
### 설명

정확한 조건은 모르겠네요. 했던 모든 행동 써보면 아래정도..? 다시 해본다고 완전히 재현이 되지는 않아요.

1. '새구' 검색
2. 스크롤 좀 내리기
3. 리스트탭 전환
4. 'test' 검색
5. 리스트탭 전환
6. 플리 하나 접근
7. 뒤로와보니 사라져있음
8. 어디를 터치하거나 스크롤하면 다시 텍스트가 노출되어있음

### 추가사항

https://github.com/user-attachments/assets/8785c44c-055a-4520-aa43-d3673221b8fd

**Comment by yongbeomkwak** [comment]
탭맨 문제라 수정이 될지 모르겠네요..
