### ISSUE TITLE
간헐적으로 검색 페이지에서 swipe로 노래 탭 접근 시 폰트 weight가 더 얇음

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#1012]
### 설명

최초 시점 :
![image](https://github.com/user-attachments/assets/7d885647-e2f2-4dbb-906b-a6c71b281a34)

swipe로 돌아옴 :
![image](https://github.com/user-attachments/assets/fde23c81-c673-40bb-aa19-0a9890e811df)

### 추가사항

재현하다보니 리스트도 가끔 이럼. 둘다 뭔가 가끔 weight가 얇아지는듯하네요

**Comment by KangTaeHoon** [comment]
이거 라이브러리 버그로 거의 포기한 상태입니다.

**Comment by baekteun** [comment]
ㅋㅋ 딱히 큰 문제도 없고 간헐적이기도해서 Low로 뒀어요
