### ISSUE TITLE
보관함 -> 리스트만들기에서 열매 개수로 막히지 않음

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#1014]
### 설명

보관함 페이지에서 리스트 만들기를 할 때 열매 2개가 필요한데, 소모하겠다고 하면 리스트 제목 입력에 진입 (열매가 부족해도 진입함) 제목 입력 후 서버에러가 토스트로 나옴

**Comment by youn9k** [comment]
#1000
