### ISSUE TITLE
설정 페이지 개인정보 처리 방침 Cell과 상세페이지의 개인정보처리방침 제목이 다른

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#1019]
### 설명

![image](https://github.com/user-attachments/assets/61f7845f-0a93-4d9e-b9b8-2e799772adc5)

![image](https://github.com/user-attachments/assets/3d0e0fb0-c974-4a8d-8beb-5b9200e7039f)

**Comment by KangTaeHoon** [comment]
두 단어가 복합된 형태이므로 띄어쓰기를 그렇게 원칙적으로 할 필요는 없을 것 같지만 다 붙이는건 너무 딱딱해 보여서
"개인정보 처리방침"으로 처리하겠습니다.
