### ISSUE TITLE
Native SPM도 구제불능인 ObjC 기반 라이브러리

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#204]
### 할 일

구글로그인은 웹으로 우회해서 해결했다.

그럼 이것들은??,,
Firebase,
Realm

### 추가사항

파베 애널리틱스, 크래시틱스는 DAU, 각종 지표 등 앱 크래시의 원인을 파악할 수 있는 너무나도 중요한 라이브러리다.

**Comment by yongbeomkwak** [comment]
1. xcframework로 만들어서 해결하거나 
2. 카르타고 되면 카르타고
3. native spm으로 전 모듈에 디펜던시 추가 (비추)

- tuist 장점인 빠른 빌드속도를 약간 포기하는 꼴이 되는거거둔요
