### ISSUE TITLE
22일 회의 때 동기화 시킬 것 

### ISSUE THREAD

**Issue by yongbeomkwak** [wakmusic/wakmusic-iOS#213]
### 할 일

- 왁타버스 URL 숨김 처리 ✅
- package.resolved 모두 동기화 후 , .package.resolved 깃 이그노어
- SSL 관련 제거 하기 ✅
- in App Purchase 삭제하기
### 추가사항
<img width="302" alt="스크린샷 2023-04-15 오후 2 28 36" src="https://user-images.githubusercontent.com/48616183/232185044-46217720-c4bb-4712-9214-e39c7b00d382.png">

_No response_

**Comment by KangTaeHoon** [comment]
왁타버스 URL 숨김 처리 [완료[

**Comment by yongbeomkwak** [comment]
인앱 결제는 추후 다른 이슈로 닫기
