### ISSUE TITLE
버전이 다름 

### ISSUE THREAD

**Issue by yongbeomkwak** [wakmusic/wakmusic-iOS#239]
### 설명

info.plist에 설정된 앱 버전이나 빌드버전이랑
트유설정이랑 따로 노는것 같아요.

**Comment by KangTaeHoon** [comment]
Tuist 설정에서 변경하면 반영되도록 설정완료.

Tuist 설정 부분
<img width="821" alt="스크린샷 2023-06-06 오후 11 52 36" src="https://github.com/wakmusic/wakmusic-iOS/assets/37323252/fd1864f3-2c65-4e63-8a65-6eb49994cebb">

결과
<img width="436" alt="스크린샷 2023-06-06 오후 11 52 57" src="https://github.com/wakmusic/wakmusic-iOS/assets/37323252/de83e522-8f4f-4f84-a472-a95f55bad5c4">
