### ISSUE TITLE
백그라운드에 앱을 장시간 놓고 있다가 다시 들어오면 음악 재생이 안됨

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#254]
### 설명

백그라운드에 앱을 장시간 놓고 있다가 다시 들어오면 음악 재생이 안됨.. 음악 누르면 재생목록에 추가는되는데,, 무반응임

자고 일어나서 켜보니 그랬음. 대략 8시간 정도..?

**Comment by KangTaeHoon** [comment]
![stateError](https://github.com/wakmusic/wakmusic-iOS/assets/37323252/249e7e45-e54e-424b-90ec-100f9712282b)

시간이 얼마나 걸려서 이런 상태인지는 판단할 필요없고, 에러상태면 플레이어 동작을 안하니까 

![스크린샷 2023-06-11 오전 12 06 12](https://github.com/wakmusic/wakmusic-iOS/assets/37323252/da23ad4c-24a1-47e4-a2ce-c154de035fe7)

<Next Step>
        player = YouTubePlayer(configuration: .init(autoPlay: false, showControls: false, showRelatedVideos: false))
        player.cue(source: .video(id: currentSong?.id ?? "")) // 곡이 있으면 .cued 없으면 .unstarted
        
        플레이어를 재할당 해주면 되지않을까 하는데, 일단 구현 담당하신 케이님 생각은 어떤가요?
        
        @youn9k @yongbeomkwak @kimdaehee0824 
        
        
        
![스크린샷 2023-06-11 오전 12 08 59](https://github.com/wakmusic/wakmusic-iOS/assets/37323252/f2d26764-baad-441e-8b36-9879e64493df)

에러 상태 체크는 PlayState+Public 파일 내에 함수에서 판단합니다.

**Comment by yongbeomkwak** [comment]
유튜브 호스트 뷰도 같이 변경하므로써 해결
