### ISSUE TITLE
앱이 수집하는 개인정보

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#317]
### 할 일

![스크린샷 2023-06-07 오후 11 51 23](https://github.com/wakmusic/wakmusic-iOS/assets/37323252/eb0aa8bb-cc0d-4455-af22-8d2c1c4c3b0f)

개인정보 처리방침이 현재 앱에서는 pdf로 등록되어있는데, 스토어에도 변경해야합니다. 

회원가입 기능 추가에 따라 개인정보가 수집되니 아래 수집 데이터도 명시해야합니다.

**Comment by yongbeomkwak** [comment]
개인 정보 처리 방침
 static.wakmusic.xyz/static/document/privacy.pdf
 
 서비스 이용 약관
  static.wakmusic.xyz/static/document/terms.pdf
