### ISSUE TITLE
로그인 방식 변경

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#329]
### 할 일

써드파티로부터 전달받은 고유 ID를 백엔드 서버로 전달하여 로그인 하였지만, 고유ID 발급 이전에 발급 된 토큰을 전달하여 백엔드에서 토큰으로 고유 ID를 발급해 로그인 하는 방식으로 변경 

<Next Step>
고유ID 대신에 토큰 + 플랫폼타입(Naver, Google, Apple)을 파람으로 전달

### 추가사항

구글은 현재 연동된거 코코아님 테스트 계정이라 바꿔야 함.

**Comment by yongbeomkwak** [comment]
네이버 
애플 완료

**Comment by yongbeomkwak** [comment]
구글까지 모두 변경완료
