### ISSUE TITLE
CI 환경 개선

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#401]
### 할 일

현재 [CI.yml](https://github.com/wakmusic/wakmusic-iOS/blob/develop/.github/workflows/CI.yml) 구축되어있는 CI는 브랜치 이름을 조건에 맞게 만들어야만 실행돼요. 하지만 이 브랜치 규칙은 왁뮤 iOS 팀의 협업 룰과는 다르게 설정되어있어서 CI는 모두 스킵되어왔어요.

CI의 실행조건에 브랜치 이름을 제외하고 PR이 올라왔을 때 실행되도록 바꾸어요.

### 추가사항

현재 CI는 브랜치 이름에 따라 특정 모듈만 빌드하는데, 특정 모듈만 빌드하는 대신 최상단 앱 모듈을 빌드/테스트를 돌리는 방향으로 방식이 바뀌어요
> 특정 모듈만 빌드할 시, CI 속도는 매우 빨라지지만 해당 모듈을 의존성으로 가진 다른 모듈들은 CI를 돌리지 않기에 코드의 안정성이 떨어져요. 시간은 조금 더 들 수 있지만 전체 모듈을 빌드해요.

---

tuist cache 기능에 대해서 조금 더 R&D를 해보아서 CI 단계에서 적용이 가능한지 확인해볼거에요. 가능하다면 CI 속도를 획기적으로 줄일 수 있을거라 기대해요.

**Comment by yongbeomkwak** [comment]
저번에 질문 드렸던 그 디펜던시 캐싱은 하나의 .yml을 통해서 결과만 다른 action에 전달하면 좋을 것 같은데 ..

**Comment by baekteun** [comment]
> 저번에 질문 드렸던 그 디펜던시 캐싱은 하나의 .yml을 통해서 결과만 다른 action에 전달하면 좋을 것 같은데 ..

디펜던시 캐싱 따로 파일 분리 없이 CI.yml에서 처리하는거 어떨까요? 캐싱하는 yml이 따로 존재하는 의미가 크게는 없는거같아서요

**Comment by yongbeomkwak** [comment]
디펜던시가 필요한 ci가 하나면 좋은 것 같습니다
