### ISSUE TITLE
모듈 정의 메서드 변경에 따른 모듈 생성 자동화 스크립트 변경

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#424]
### 할 일

현재 있는 모듈 생성 스크립트는 이전 `.makeModule` 을 이용한 모듈 정의를 하였으나 `.module` 을 이용하는걸 권장하도록 바뀌었으니 모듈 생성 스크립트를 변경합니다

**Comment by yongbeomkwak** [comment]
확인했습니다 ~
