### ISSUE TITLE
RepositoryImpl 객체는 struct? class?

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#432]
### 할 일

RepositoryImpl 객체는 struct? class? 

잘 모르겠어서 공유하여 고민하고자 합니다.

**Comment by yongbeomkwak** [comment]
class 나쁘지 않아보입니다 .

**Comment by baekteun** [comment]
보편적으로 여러 UseCase에서 공유되어서 쓰이게 되다보니 class가 적절할거같아요!
