### ISSUE TITLE
빌드 속도가 매우 느려진 현상 해결

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#461]
### 할 일

SwiftLint가 config파일의 경로를 기준으로 exclude할 파일들을 모두 찾아놓는거같은데 이때 파일들을 찾느라 걸리는 인덱싱 시간이 각 모듈별로 실행되다보니 성능이 느려지는거같네요.. Needle을 린트 대상으로 제외하려고 했으나 이러면 인덱싱이 너무 오래 걸릴거같아서 Needle이 유발하는 error lint들의 rule들을 disabled해야할거같아요.

**Comment by yongbeomkwak** [comment]
그러면 시간이 린트로부터 거리가 먼 파일이 올래걸리는건가요 ??

**Comment by yongbeomkwak** [comment]
일단 exclude에 하나라도 추가되어있으면 일단 10초 추가군요 ..

**Comment by baekteun** [comment]
기기따라 오차가 좀 더 있을 수 있을거같긴한데 일단 스크립트 실행 시간이 1초이상은 먹을거같네요

**Comment by yongbeomkwak** [comment]
흠 알겠습니다 수고하셨습니다 :)
