### ISSUE TITLE
써드파티 SDK 업데이트

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#529]
### 할 일

이걸 해야 각 SDK에서 작성한 Privacy Manifest를 적용할 수 있어요. 
1년동안 업데이트 안했으니 아마도.. 뭔 일이 일어나긴 할듯?

**Comment by yongbeomkwak** [comment]
별도의 브랜치에서 해야하나요 ??

**Comment by KangTaeHoon** [comment]
> 별도의 브랜치에서 해야하나요 ??

네, 업데이트 변경 점에따라 앱 전역에서 수정이 필요할 수 있어서 그러려고합니다.

**Comment by yongbeomkwak** [comment]
> > 별도의 브랜치에서 해야하나요 ??
> 
> 네, 업데이트 변경 점에따라 앱 전역에서 수정이 필요할 수 있어서 그러려고합니다.

흠 .. 작업 중에하는게 맞을 지 작업 끝나고 하고 하는게 맞는지 잘 모르겠네요

**Comment by baekteun** [comment]
#537 에서 해결했어요
