### ISSUE TITLE
사용 중인 오픈소스 정리

### ISSUE THREAD

**Issue by youn9k** [wakmusic/wakmusic-iOS#624]
### 할 일

<img src="https://github.com/wakmusic/wakmusic-iOS/assets/60254939/3500dd02-bc79-4441-b239-ea2f7db2cfa2" width=50% height=50%>

오픈소스 정리하기

**Comment by youn9k** [comment]
PanModal (PR 승인시)
MarqueeLabel (노래 상세에 이 기능이 빠진다면)
YouTubePlayerKit(제거 확정)

**Comment by KangTaeHoon** [comment]
PanModal 제거 확정
