### ISSUE TITLE
새 공지사항 인디케이터 기능 구현 

### ISSUE THREAD

**Issue by youn9k** [wakmusic/wakmusic-iOS#674]
### 할 일

- [x] NoticeDomain 신규 API 추가
- [X] 읽은 공지사항 유저디폴트에 저장
- [x] 공지사항을 전부 읽었는지 비교 로직 구현

**Comment by KangTaeHoon** [comment]
참고) 공지팝업을 통해 공지상세로 진입할 수도 있음.
<img width="278" alt="스크린샷 2024-06-26 오후 11 10 41" src="https://github.com/wakmusic/wakmusic-iOS/assets/37323252/42829d0d-060a-4042-b574-6cf8ab792fec">
