### ISSUE TITLE
비로그인 상태로 열매 뽑기 화면 진입 시 크래쉬

### ISSUE THREAD

**Issue by youn9k** [wakmusic/wakmusic-iOS#758]
### 설명

https://github.com/wakmusic/wakmusic-iOS/assets/60254939/a029ff1e-05bc-490e-b6db-f169a5e7f508

비 로그인 시 버튼 비활성화 하는게 가장 쉬울듯

**Comment by KangTaeHoon** [comment]
로그인 화면 띄우는게 맞습니다.
