### ISSUE TITLE
보관함 탭 남은 작업

### ISSUE THREAD

**Issue by youn9k** [wakmusic/wakmusic-iOS#769]
### 할 일

- [x] 좋아요 탭 구현
- [x] 플레이리스트 상세화면 연결
- [x] 재생목록에 추가 기능
- [x] 재생버튼 이벤트
- [x] DTO 수정
- [x] #775

|--|--|
|--|--|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-07-11 at 19 01 08](https://github.com/wakmusic/wakmusic-iOS/assets/60254939/458bf476-ab2c-4e5a-8f90-4f9c812e9588) | ![Simulator Screenshot - iPhone 15 Pro - 2024-07-11 at 18 59 45](https://github.com/wakmusic/wakmusic-iOS/assets/60254939/9309144b-3760-44d3-ae8f-dd1617fd03fa) |

**Comment by baekteun** [comment]
재생목록 추가와 재생하기 기능 #930 에서 해치워져버렸어요(?) @youn9k 혹시나 로직 더블체크 부탁드려요
