### ISSUE TITLE
네트워크로 인한 예상치 못한 에러 발생 시 토스트 팝업 

### ISSUE THREAD

**Issue by yongbeomkwak** [wakmusic/wakmusic-iOS#77]

**Comment by KangTaeHoon** [comment]
<img width="775" alt="스크린샷 2023-02-20 오전 4 56 33" src="https://user-images.githubusercontent.com/37323252/219971965-d0dc35e5-e8b6-4fe8-9464-b5969e52e088.png">

토스트는 NetworkMudole > BaseRemoteDataSource > func defaultRequest 에서 스샷처럼 추가해주면 가능한데, MoyaError로 변환 하는 가드문을 통과하지 못하여 그 윗줄에 넣어 뒀습니다.

**Comment by yongbeomkwak** [comment]
기본 에러는 넣었지만 분기와 한글화 필요
