### ISSUE TITLE
재생목록 화면 Drag로 dismiss 시 검은 배경이 보여짐

### ISSUE THREAD

**Issue by baekteun** [wakmusic/wakmusic-iOS#800]
### 설명

https://github.com/user-attachments/assets/75a36188-f9bb-4e83-87a9-9623e187234c

**Comment by KangTaeHoon** [comment]
이거, 재생목록 present 스타일이 overFullScreen에서 fullScreen으로 변경되어서 그래요. (뷰컨 라이프사이클이 돌아야 하는 화면이 있어서 변경했음)
사실 드래그 기능이 네비게이션 바 있는부분만 동작하는 한정된 기능인데, 드래그 dismiss 기능을 빼는게 좋겠습니다.

**Comment by baekteun** [comment]
엇 드래그 기능 나름 사용성에 좋을거같은데 그냥 빼도 괜찮으려나요? 어 물론 제가 제스쳐 기반으로 행동을 많이 해서 그런걸 수도 있긴한데..

**Comment by KangTaeHoon** [comment]
아니면, showBottomSheet() 바텀시트 유틸 이용해서 프레젠트 하는것도 방법이겠네요.
`showBottomSheet(content: playlistViewController, size: .fixed(APP_HEIGHT()))`

**Comment by KangTaeHoon** [comment]
> 아니면, showBottomSheet() 바텀시트 유틸 이용해서 프레젠트 하는것도 방법이겠네요. `showBottomSheet(content: playlistViewController, size: .fixed(APP_HEIGHT()))`

아,, 이것도 오버풀스크린인걸로
