### ISSUE TITLE
Notification Name 개선

### ISSUE THREAD

**Issue by youn9k** [wakmusic/wakmusic-iOS#970]
### 할 일

<img width="986" alt="image" src="https://github.com/user-attachments/assets/743e9bdb-3327-42f4-bdf5-75fb66470c01">

### 문제점

명칭들이 모호한 감이 있습니다. 예를 들어 `playlistRefresh` 라면 플레이리스트가 리프레쉬 되었다는건가? 필요하다는건가? 모호하고, `showSongCart` 라면 songCart가 보여져야된다는건가? 이미 보여졌다는건가? 등 모호한 표현으로 인해 사용하는 곳에 혼동을 줄 수 있습니다.

### 개선 방향

`should`, `did`, `will` 등 swift 에서 자주 사용하는 prefix 들을 사용하여 개선하면 어떨까요?

ex) `playlistRefresh` -> `plalistShouldRefresh` 또는 `shouldRefreshPlaylist`
ex) `showSongCart` -> `songCartShouldShow` 또는 `shouldShowSongCart`

더 좋은 개선 방향이 있다면 코멘트에 달아주세요!

**Comment by KangTaeHoon** [comment]
음, 이전부터 좀 거슬리긴했는데 should, did, will같은 키워드가 앞에오면 좋겠네요. 
추가로 should와 will의 구분도 있었으면 합니다. 아래에 예시입니다.

✅ :: shouldRefreshPlaylist, willShowSongCart
❌ :: plalistShouldRefresh, songCartShouldShow

**Comment by yongbeomkwak** [comment]
저도 찬성합니다 ~

**Comment by youn9k** [comment]
> 음, 이전부터 좀 거슬리긴했는데 should, did, will같은 키워드가 앞에오면 좋겠네요. 추가로 should와 will의 구분도 있었으면 합니다. 아래에 예시입니다.
> 
> ✅ :: shouldRefreshPlaylist, willShowSongCart ❌ :: plalistShouldRefresh, songCartShouldShow

접두사들을 앞으로 빼는게 더 직관적이네요 👍

**Comment by baekteun** [comment]
<img width="629" alt="image" src="https://github.com/user-attachments/assets/aaf28a60-051d-40ce-ad3f-8491a88b92b1">

**Comment by youn9k** [comment]
> <img alt="image" width="629" src="https://private-user-images.githubusercontent.com/74440939/354799083-aaf28a60-051d-40ce-ad3f-8491a88b92b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjcyNTUsIm5iZiI6MTcyMjY2Njk1NSwicGF0aCI6Ii83NDQ0MDkzOS8zNTQ3OTkwODMtYWFmMjhhNjAtMDUxZC00MGNlLWFkM2YtODQ5MWE4OGI5MmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA2MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNGZmM2YwNjQwYWViNTUwNGU5ZTQ2ZTM0MDVkYzQ1MGQxM2JiMjBiMzlmZjYyNTU2NzZkNTFlM2ZlMzZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PqhRRSQ9ZYSqOb8OqMxtJpT4yWEgr43iii0CoX_tJ60"> 수정완

오 이미 컨벤션이 작성된게 있었네요 잘 지켜지지 않은게 아쉽..😦
