### ISSUE TITLE
보관함 페이지에 접근을 안해도 유저의 플리와 좋아요 리스트를 가져오는 현상

### ISSUE THREAD

**Issue by KangTaeHoon** [wakmusic/wakmusic-iOS#978]
### 설명
+ 보관함페이지에 접근하면 플리와 좋아요 리스트가 추가로 호출

### 내 정보 페이지 접근 후 호출된 api 목록
[GET] ~~/app/check
[GET] ~~/user/profile
[GET] ~~/user/playlists << ?
[GET] ~~/user/likes << ?
[GET] ~~notice/ids
[GET] ~~/notice/popup

그리고 보관함으로 가면 
[GET] ~~/user/playlists
[GET] ~~/user/likes

또 호출됨

**Comment by baekteun** [comment]
내 정보 페이지가 아니여도 앱이 실행되는 순간 호출하는거같아요
